# Importações das URLs
import urls.br_mangas.main as agr_01
import urls.crystal_scan.main as agr_02
import urls.argos_comics.main as agr_03
# import urls.argos_hentai.main as agr_04
import urls.mangás_chan.main as agr_05
import urls.ler_mangá.main as agr_06
import urls.tsuki.main as agr_07
import urls.yomumangás.main as agr_08
import urls.slimeread.main as agr_09
import urls.flower_manga.main as agr_10
import urls.ler_manga_online.main as agr_11
import urls.manga_br.main as agr_12
import urls.projeto_scanlator.main as agr_13
import urls.hentai_teca.main as agr_14
import urls.argos_scan.main as agr_15
import urls.nicomanga.main as agr_16
import urls.momo_no_hana.main as agr_17
import urls.manhastro.main as agr_18
import urls.valkyrie_scan.main as agr_19
import urls.limbo_scan.main as agr_20
import urls.nobre_scan.main as agr_21
import urls.iris_scanlator.main as agr_22
import urls.novelmic.main as agr_23
import urls.norte_rose.main as agr_24
import urls.lscans.main as agr_25
import urls.minitwoscan.main as agr_26
import urls.demonsect.main as agr_27
import urls.moonwitchinlovescan.main as agr_28
import urls.hikari_scan.main as agr_29
import urls.luratoon.main as agr_30
import urls.mode_scanlator.main as agr_31
import urls.cerisetoon.main as agr_32
import urls.sinensistoon.main as agr_33
import urls.xyaoi.main as agr_34